# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: #178c94;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background: #02E3B3; \n"
"    border : 3px solid #297BA0;\n"
"    border-radius: 40px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_transword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_transword.setGeometry(QtCore.QRect(100, 120, 451, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.pushButton_transword.setFont(font)
        self.pushButton_transword.setObjectName("pushButton_transword")
        self.pushButton_translator = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_translator.setGeometry(QtCore.QRect(570, 480, 451, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.pushButton_translator.setFont(font)
        self.pushButton_translator.setObjectName("pushButton_translator")
        self.pushButton_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_settings.setGeometry(QtCore.QRect(1040, 480, 451, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.pushButton_settings.setFont(font)
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.pushButton_regularlessons = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_regularlessons.setGeometry(QtCore.QRect(100, 480, 451, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.pushButton_regularlessons.setFont(font)
        self.pushButton_regularlessons.setObjectName("pushButton_regularlessons")
        self.pushButton_knowledgetest = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_knowledgetest.setGeometry(QtCore.QRect(1040, 120, 451, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.pushButton_knowledgetest.setFont(font)
        self.pushButton_knowledgetest.setObjectName("pushButton_knowledgetest")
        self.pushButton_eartraining = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_eartraining.setGeometry(QtCore.QRect(570, 120, 451, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(48)
        self.pushButton_eartraining.setFont(font)
        self.pushButton_eartraining.setObjectName("pushButton_eartraining")
        self.label_welcome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(100, 30, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(30)
        font.setItalic(True)
        self.label_welcome.setFont(font)
        self.label_welcome.setObjectName("label_welcome")
        self.label_programname = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_programname.setGeometry(QtCore.QRect(600, 10, 411, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(58)
        font.setItalic(True)
        self.label_programname.setFont(font)
        self.label_programname.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_programname.setObjectName("label_programname")
        self.label_level = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_level.setGeometry(QtCore.QRect(1130, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_level.setFont(font)
        self.label_level.setObjectName("label_level")
        self.label_balance = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_balance.setGeometry(QtCore.QRect(1310, 30, 171, 51))
        self.label_balance.setMinimumSize(QtCore.QSize(171, 51))
        self.label_balance.setMaximumSize(QtCore.QSize(171, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.label_balance.setFont(font)
        self.label_balance.setObjectName("label_balance")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_transword.setText(_translate("MainWindow", "Translate \n"
"the word"))
        self.pushButton_translator.setText(_translate("MainWindow", "Translator"))
        self.pushButton_settings.setText(_translate("MainWindow", "Settings"))
        self.pushButton_regularlessons.setText(_translate("MainWindow", "Regular\n"
"lessons"))
        self.pushButton_knowledgetest.setText(_translate("MainWindow", "Knowledge \n"
"test"))
        self.pushButton_eartraining.setText(_translate("MainWindow", "Ear \n"
"training"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome!"))
        self.label_programname.setText(_translate("MainWindow", "EngMaster"))
        self.label_level.setText(_translate("MainWindow", "Level:"))
        self.label_balance.setText(_translate("MainWindow", "Balance:"))
