# Form implementation generated from reading ui file 'autoritation.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(383, 403)
        font = QtGui.QFont()
        font.setPointSize(14)
        Form.setFont(font)
        Form.setStyleSheet("QWidget{\n"
"    background: #178c94;\n"
"    \n"
"}\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 20px;\n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"    background: #02E3B3; \n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"}")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 290, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 290, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 160, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background rgb(170, 170, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 220, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(110, 40, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_status = QtWidgets.QLabel(parent=Form)
        self.label_status.setGeometry(QtCore.QRect(90, 130, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_status.setFont(font)
        self.label_status.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_status.setStyleSheet("color: rgb(255, 255, 0)")
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Sign in"))
        self.pushButton_2.setText(_translate("Form", "New Account"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Login"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Password"))
        self.label.setText(_translate("Form", "Welcome to"))
        self.label_2.setText(_translate("Form", "EngMaster!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
