# Form implementation generated from reading ui file 'regularlessons.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: #178c94;\n"
"}\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}\n"
"\n"
"QPushButton { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ready = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ready.setGeometry(QtCore.QRect(860, 700, 621, 121))
        self.ready.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.ready.setFont(font)
        self.ready.setStyleSheet("background-color: #02E3B3;")
        self.ready.setObjectName("ready")
        self.levelnumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.levelnumber.setGeometry(QtCore.QRect(40, 10, 771, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(80)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.levelnumber.setFont(font)
        self.levelnumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.levelnumber.setObjectName("levelnumber")
        self.progress = QtWidgets.QLabel(parent=self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(910, 10, 641, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(80)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.progress.setFont(font)
        self.progress.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.progress.setObjectName("progress")
        self.russianword = QtWidgets.QLabel(parent=self.centralwidget)
        self.russianword.setGeometry(QtCore.QRect(210, 440, 1192, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(90)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.russianword.setFont(font)
        self.russianword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.russianword.setObjectName("russianword")
        self.notready = QtWidgets.QPushButton(parent=self.centralwidget)
        self.notready.setGeometry(QtCore.QRect(100, 700, 621, 121))
        self.notready.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.notready.setFont(font)
        self.notready.setObjectName("notready")
        self.englishword = QtWidgets.QLabel(parent=self.centralwidget)
        self.englishword.setGeometry(QtCore.QRect(430, 230, 754, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(90)
        font.setBold(True)
        font.setWeight(75)
        self.englishword.setFont(font)
        self.englishword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.englishword.setObjectName("englishword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ready.setText(_translate("MainWindow", "Запомнил"))
        self.levelnumber.setText(_translate("MainWindow", "Номер урока"))
        self.progress.setText(_translate("MainWindow", "Прогресс"))
        self.russianword.setText(_translate("MainWindow", "Перевод на русский"))
        self.notready.setText(_translate("MainWindow", "Повторить"))
        self.englishword.setText(_translate("MainWindow", "English word"))
