# Form implementation generated from reading ui file 'translator.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: #178c94;\n"
"}\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}\n"
"\n"
"QPushButton { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}\n"
"\n"
"QComboBox { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 0px;    \n"
"}\n"
"\n"
"QComboBox:drop-down { \n"
"    width: 25px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.translate_but = QtWidgets.QPushButton(parent=self.centralwidget)
        self.translate_but.setGeometry(QtCore.QRect(80, 740, 1451, 111))
        self.translate_but.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.translate_but.setFont(font)
        self.translate_but.setStyleSheet("background-color: #02E3B3;")
        self.translate_but.setObjectName("translate_but")
        self.lang1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lang1.setGeometry(QtCore.QRect(240, 20, 361, 101))
        self.lang1.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lang1.setFont(font)
        self.lang1.setObjectName("lang1")
        self.lang2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lang2.setGeometry(QtCore.QRect(1030, 20, 361, 101))
        self.lang2.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lang2.setFont(font)
        self.lang2.setObjectName("lang2")
        self.langchange = QtWidgets.QPushButton(parent=self.centralwidget)
        self.langchange.setGeometry(QtCore.QRect(720, 20, 191, 111))
        self.langchange.setMinimumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.langchange.setFont(font)
        self.langchange.setStyleSheet("image: url(ico/icon-swap.png);")
        self.langchange.setText("")
        self.langchange.setObjectName("langchange")
        self.input = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.input.setGeometry(QtCore.QRect(140, 150, 611, 571))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input.setFont(font)
        self.input.setStyleSheet("border : 7px solid #ffffff;\n"
"border-radius: 45px;   \n"
"color: #ffffff;\n"
"padding-top:10;\n"
"padding-left:10; \n"
"padding-bottom:10; \n"
"padding-right:10;\n"
"")
        self.input.setPlainText("")
        self.input.setObjectName("input")
        self.result = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.result.setGeometry(QtCore.QRect(880, 150, 611, 571))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("border : 7px solid #ffffff;\n"
"border-radius: 45px;   \n"
"color: #ffffff;\n"
"padding-top:10;\n"
"padding-left:10; \n"
"padding-bottom:10; \n"
"padding-right:10;\n"
"")
        self.result.setReadOnly(True)
        self.result.setPlainText("")
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.translate_but.setText(_translate("MainWindow", "Перевести"))
        self.lang1.setText(_translate("MainWindow", "Русский"))
        self.lang2.setText(_translate("MainWindow", "Английский"))
        self.input.setPlaceholderText(_translate("MainWindow", "Введите текст для перевода"))
        self.result.setPlaceholderText(_translate("MainWindow", "Здесь появится перевод"))
