# Form implementation generated from reading ui file 'transword.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1518, 809)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: #178c94;\n"
"}\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}\n"
"\n"
"QPushButton { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("whiteangle.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(120, 120))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("question.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 70))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.wordshow = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordshow.sizePolicy().hasHeightForWidth())
        self.wordshow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(90)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.wordshow.setFont(font)
        self.wordshow.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.wordshow.setObjectName("wordshow")
        self.gridLayout.addWidget(self.wordshow, 1, 0, 1, 4)
        self.wordinput = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(50)
        self.wordinput.setFont(font)
        self.wordinput.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.wordinput.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.wordinput.setStyleSheet("padding: 20 px;")
        self.wordinput.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.wordinput.setObjectName("wordinput")
        self.gridLayout.addWidget(self.wordinput, 2, 1, 1, 2)
        self.false_ans = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.false_ans.sizePolicy().hasHeightForWidth())
        self.false_ans.setSizePolicy(sizePolicy)
        self.false_ans.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.false_ans.setFont(font)
        self.false_ans.setStyleSheet("color: rgb(255, 80, 37)\n"
"")
        self.false_ans.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.false_ans.setObjectName("false_ans")
        self.gridLayout.addWidget(self.false_ans, 0, 2, 1, 2)
        self.right_ans = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_ans.sizePolicy().hasHeightForWidth())
        self.right_ans.setSizePolicy(sizePolicy)
        self.right_ans.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.right_ans.setFont(font)
        self.right_ans.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.right_ans.setStyleSheet("color: rgb(0, 216, 0);")
        self.right_ans.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.right_ans.setObjectName("right_ans")
        self.gridLayout.addWidget(self.right_ans, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1518, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wordshow.setText(_translate("MainWindow", "Word to check"))
        self.wordinput.setPlaceholderText(_translate("MainWindow", "Enter the answer"))
        self.false_ans.setText(_translate("MainWindow", "False : 0"))
        self.right_ans.setText(_translate("MainWindow", "Right : 0"))
