# Form implementation generated from reading ui file 'knowledgetest.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: #178c94;\n"
"}\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}\n"
"\n"
"QPushButton { \n"
"    background: #09C0CC ; \n"
"    color: white;\n"
"    border : 2px solid #297BA0;\n"
"    border-radius: 30px;    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.answer_a = QtWidgets.QLabel(parent=self.centralwidget)
        self.answer_a.setGeometry(QtCore.QRect(70, 240, 701, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.answer_a.setFont(font)
        self.answer_a.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.answer_a.setObjectName("answer_a")
        self.button_a = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_a.setGeometry(QtCore.QRect(140, 700, 311, 151))
        self.button_a.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.button_a.setFont(font)
        self.button_a.setObjectName("button_a")
        self.button_b = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_b.setGeometry(QtCore.QRect(480, 700, 311, 151))
        self.button_b.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.button_b.setFont(font)
        self.button_b.setObjectName("button_b")
        self.button_c = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_c.setGeometry(QtCore.QRect(820, 700, 311, 151))
        self.button_c.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.button_c.setFont(font)
        self.button_c.setObjectName("button_c")
        self.button_d = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_d.setGeometry(QtCore.QRect(1160, 700, 311, 151))
        self.button_d.setMinimumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.button_d.setFont(font)
        self.button_d.setObjectName("button_d")
        self.answer_b = QtWidgets.QLabel(parent=self.centralwidget)
        self.answer_b.setGeometry(QtCore.QRect(760, 240, 701, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.answer_b.setFont(font)
        self.answer_b.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.answer_b.setObjectName("answer_b")
        self.answer_c = QtWidgets.QLabel(parent=self.centralwidget)
        self.answer_c.setGeometry(QtCore.QRect(70, 440, 701, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.answer_c.setFont(font)
        self.answer_c.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.answer_c.setObjectName("answer_c")
        self.answer_d = QtWidgets.QLabel(parent=self.centralwidget)
        self.answer_d.setGeometry(QtCore.QRect(760, 440, 701, 139))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.answer_d.setFont(font)
        self.answer_d.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.answer_d.setObjectName("answer_d")
        self.Question = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.Question.setGeometry(QtCore.QRect(180, 20, 1191, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.Question.setFont(font)
        self.Question.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Question.setStyleSheet("color: rgb(255, 255, 255);")
        self.Question.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Question.setReadOnly(True)
        self.Question.setPlainText("")
        self.Question.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.Question.setObjectName("Question")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.answer_a.setText(_translate("MainWindow", "Вариант А"))
        self.button_a.setText(_translate("MainWindow", "А"))
        self.button_b.setText(_translate("MainWindow", "B"))
        self.button_c.setText(_translate("MainWindow", "C"))
        self.button_d.setText(_translate("MainWindow", "D"))
        self.answer_b.setText(_translate("MainWindow", "Вариант B"))
        self.answer_c.setText(_translate("MainWindow", "Вариант C"))
        self.answer_d.setText(_translate("MainWindow", "Вариант D"))
